post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end

use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'

target 'MKLoRaTrackerSDK_Example' do
  pod 'MKLoRaTrackerSDK', :path => '../'
  
  pod 'MLInputDodger'
    pod 'iOSDFULibrary','4.6.1'
    pod 'FMDB'
    pod 'CircleProgressBar'
    pod 'Masonry'
    pod 'MBProgressHUD'
    pod 'MJRefresh'
    pod 'Toast'
    pod 'YYKit'

  target 'MKLoRaTrackerSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
