use_frameworks!

platform :ios, '9.0'

target 'MKLoRaTrackerSDK_Example' do
  pod 'MKLoRaTrackerSDK', :path => '../'

  target 'MKLoRaTrackerSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
